{{/* TODO: multiple workers with one service (for dns) per worker */}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "vela-worker.fullname" . }}
  labels:
    {{- include "vela-worker.labels" . | nindent 4 }}
spec:
  # Each worker needs a unique identity in VELA_WORKER_ADDR.
  # So, each worker is essentially a singleton.
  replicas: 1
  selector:
    matchLabels:
      {{- include "vela-worker.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "vela-worker.selectorLabels" . | nindent 8 }}
      {{- if .Values.podLabels }}
        {{ toYaml .Values.podLabels | nindent 8 }}
      {{- end }}
      annotations:
        checksum/secrets: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      {{- if .Values.podAnnotations }}
        {{ toYaml .Values.podAnnotations | nindent 8 }}
      {{- end }}
    spec:
    {{- if and (semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion) (.Values.topologySpreadConstraints) }}
      {{- with .Values.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- end }}
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "vela-worker.fullname" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
      containers:
        - name: worker
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name:  {{ .Values.service.scheme | lower }}
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.service.port }}
              scheme: {{ .Values.service.scheme | upper }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: VELA_WORKER_ADDR_OLD
              {{/* TODO: multiple workers needs different template for service name */}}
              value: {{ .Values.service.scheme }}://{{ include "vela-worker.fullname" . }}:{{ .Values.service.port }}
            - name: WORKER_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: WORKER_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: WORKER_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: WORKER_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: VELA_WORKER_ADDR_SCHEME
              value: {{ .Values.service.scheme }}
            - name: VELA_WORKER_ADDR_PORT
              value: {{ .Values.service.port | quote }}
            - name: VELA_WORKER_ADDR
              {{/* $() provides for k8s-level env substitution similar to bash ${} */}}
              value: $(VELA_WORKER_ADDR_SCHEME)://$(WORKER_POD_NAME):$(VELA_WORKER_ADDR_PORT)
          envFrom:
            - configMapRef:
                name: {{ include "vela-worker.fullname" . }}
          {{- range .Values.extraSecretNamesForEnvFrom }}
            - secretRef:
                name: {{ . }}
          {{- end }}
        {{- with .Values.extraVolumeMounts }}
          volumeMounts:
            {{ toYaml . | nindent 12 }}
        {{- end }}
    {{- if .Values.extraVolumes }}
      volumes:
        {{ toYaml .Values.extraVolumes | nindent 8}}
    {{- end }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
