apiVersion: v1
kind: Service
metadata:
  name: {{ include "drone.fullname" . }}
  annotations:
    {{- toYaml .Values.service.annotations | nindent 4 }}
  labels:
    {{- include "drone.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  {{- range $key, $val := .Values.service.ports }}
    - port: {{ if kindIs "string" $val.port }}{{ tpl $val.port $ }}{{ else }}{{ $val.port }}{{ end }}
      targetPort: {{ if kindIs "string" $val.targetPort }}{{ tpl $val.targetPort $ }}{{ else }}{{ $val.targetPort }}{{ end }}
      protocol: TCP
      name: {{ $key }}
  {{- end }}
  selector:
    {{- include "drone.selectorLabels" . | nindent 4 }}
